

GET http://localhost:5066/api/health

###

GET http://localhost:5066/api/collection/?skip=0&limit=1

###

POST http://localhost:5066/api/collection/
Content-Type: application/json

{
    "name": "Hold",
    "userId": Null,
    "description": "this is collection 2",
    "thumbnail": "this is link 3",
    "contentIds": []
}