

GET http://localhost:5066/api/v1/health

###

GET http://localhost:5066/api/v1/collection/?skip=0&limit=3

###

POST http://localhost:5066/api/v1/collection/
Content-Type: application/json

{
    "name": "Hold",
    "userId": null,
    "description": "this is collection 2",
    "thumbnail": "this is link 3",
    "contentIds": [],
    "createdDate": "2020-01-01T00:00:00.000Z"
}