
@id=6470caf69a419a29f22cb867
GET http://localhost:5066/api/v1/health

###
GET http://localhost:5066/api/v1/collection/debug/{{id}}
###
GET http://localhost:5066/api/v1/collection/?skip=0&limit=3
###
GET http://localhost:5066/api/v1/collection/search/?name=HE
###
GET http://localhost:5066/api/v1/collection/suggest/?limit=2
###
POST http://localhost:5066/api/v1/collection/
Content-Type: application/json

{
    "name": "Hold",
    "userId": null,
    "description": "this is collection 2",
    "thumbnail": "this is link 3",
    "contentIds": ["6470b92d7b21a9a06e26cc8b"],
    "createdDate": "2020-01-01T00:00:00.000Z"
}
###
@id=647192168229721a1b3ebde2
GET http://localhost:5066/api/v1/content/collection?collectionid={{id}}&skip=0&limit=1