@id = 646f6f46739418a6bc8191d3
@contentid = 5f9f6f46739418a6bc8191d3
GET http://localhost:5066/api/v1/comment/content/?skip=0&limit=10

###

POST  http://localhost:5066/api/v1/comment/debug/
Content-Type: application/json

{
    "userId": null,
    "contentId": "5f9f6f46739418a6bc8191d3",
    "text": "This is reply for 23332",
    "parentCommentIds": null,
    "createDate": "2023-05-25T14:23:02.107Z",
    "nOfLikes": 1,
    "nOfChildComments": 0
  }