@id = 647086b000478caf34cac0f9
@contentid = 5f9f6f46739418a6bc8191d3
GET http://localhost:5066/api/v1/comment/content/?contentid={{contentid}}&skip=0&limit=10
###
GET  http://localhost:5066/api/v1/comment/content/?limit=3
###
GET http://localhost:5066/api/v1/comment/debug/{{id}}
###
POST  http://localhost:5066/api/v1/comment/
Content-Type: application/json

{
    "userId": null,
    "contentId": "5f9f6f46739418a6bc8191d3",
    "text": "This is root comment 44",
    "parentCommentId": null,
    "createDate": "2023-05-25T14:23:02.107Z",
    "nOfLikes": 1,
    "nOfChildComments": 0
}

