@id=64704ecc79725509dc2e188e
@type=story

GET http://localhost:5066/api/v1/content/debug/{{id}}
###
GET http://localhost:5066/api/v1/health
###
GET http://localhost:5066/api/v1/content/?skip=1&limit=2
###

GET http://localhost:5066/api/v1/content/search/?name=ho&skip=0&limit=1
```
###

GET http://localhost:5066/api/v1/content/related/?type=story&id={{id}}
###

POST http://localhost:5066/api/v1/content
Content-Type: application/json

{
    "debug": false,
    "name": "aas",
    "userID": null,
    "mainGraphicUrl": "hold",
    "nOfStars": 1,
    "nOfFavs": 1,
    "nOfComments": 1,
    "nOfShares": 1,
    "caption": "Hold",
    "description": "Hold",
    "content": "Content Holding",
    "type": "story",
    "createDate": "2023-05-25T14:01:38.594Z",
    "catagories": [
      "story",
      "batrieu",
      "lichsu"
    ],
    "graphics": []
}

###

DELETE http://localhost:5066/api/v1/content/{{id}}

###

PUT  http://localhost:5066/api/v1/content/{{id}}
Content-Type: application/json

{
    "debug": false,
    "name": "SchemeHolding4444",
    "userID": null,
    "mainGraphicUrl": "hold",
    "nOfStars": 1,
    "nOfFavs": 1,
    "nOfComments": 1,
    "nOfShares": 1,
    "caption": "Hold",
    "description": "Hold",
    "content": "Content Holding",
    "type": "story",
    "createDate": "2023-05-25T14:01:38.594Z",
    "catagories": [
      "story",
      "batrieu",
      "lichsu"
    ],
    "graphics": []
}